name: Lint and Test
on:
  pull_request:
    branches:
      - main
      - develop
  workflow_call:
jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    services:
      database:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: kaboor
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run tests
        env:
          JWT_PRIVATE_KEY: mRmdusYm3FaYJhP1AQ183qxWEbZ-4N0jOYhLRdU7Bwg
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/kaboor
        run: npm run test
