name: Lint and Test
on:
  pull_request:
    branches:
      - main
      - develop
  workflow_call:
jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    services:
      test-service:
        image: docker/cowsay
        # image: ignferry/bcr-database
        # env:
        #   POSTGRES_USER: postgres
        #   POSTGRES_PASSWORD: postgres
        #   POSTGRES_DB: bcr_management_dashboard
        # options: >-
        #   --health-cmd pg_isready
        #   --health-interval 10s
        #   --health-timeout 5s
        #   --health-retries 5
        # ports:
        #   - 5432:5432
    container:
      image: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run tests
        env:
          JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/bcr_management_dashboard
        run: npm run test